/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface':                    '#f9f9f7',
        'surface-dim':               '#dadad8',
        'surface-bright':            '#f9f9f7',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f4f4f2',
        'surface-container':         '#eeeeec',
        'surface-container-high':    '#e8e8e6',
        'surface-container-highest': '#e2e3e1',
        'surface-variant':           '#e2e3e1',
        'on-surface':                '#1a1c1b',
        'on-surface-variant':        '#434842',
        'inverse-surface':           '#2f3130',
        'inverse-on-surface':        '#f1f1ef',
        'outline':                   '#747872',
        'outline-variant':           '#c3c8c0',
        'surface-tint':              '#516352',
        'primary':                   '#4e604f',
        'on-primary':                '#ffffff',
        'primary-container':         '#677967',
        'on-primary-container':      '#f7fff3',
        'primary-fixed':             '#d4e8d2',
        'primary-fixed-dim':         '#b8ccb7',
        'on-primary-fixed':          '#0f1f12',
        'on-primary-fixed-variant':  '#3a4b3b',
        'inverse-primary':           '#b8ccb7',
        'secondary':                 '#5a605b',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#dbe1db',
        'on-secondary-container':    '#5e6460',
        'secondary-fixed':           '#dee4de',
        'secondary-fixed-dim':       '#c2c8c2',
        'on-secondary-fixed':        '#171d19',
        'on-secondary-fixed-variant':'#424844',
        'tertiary':                  '#72545b',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#8c6c73',
        'on-tertiary-container':     '#fffbff',
        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'background':                '#f9f9f7',
        'on-background':             '#1a1c1b',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm:      '0.25rem',
        md:      '0.75rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1.5rem',
        full:    '9999px',
      },
      spacing: {
        'unit':                '8px',
        'stack-sm':            '8px',
        'stack-md':            '16px',
        'stack-lg':            '32px',
        'gutter':              '24px',
        'margin-mobile':       '16px',
        'margin-desktop':      '48px',
        'container-max-width': '1200px',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl':       ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':       ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile':['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':          ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm':          ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      boxShadow: {
        sm:  '0 2px 4px rgba(0,0,0,0.02)',
        md:  '0 12px 24px rgba(0,0,0,0.05)',
        lg:  '0 20px 40px rgba(0,0,0,0.08)',
      },
      maxWidth: {
        'container-max-width': '1200px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
